### ISSUE TITLE
Simple_Calculator ticket - 1

### ISSUE THREAD

**Issue by Rumbie-Mudzie7** [Hlamulo-Mav/Simple_Calculator#1]
Impressive work so far Team, however, please research more on how to create a more profound readme file.

**Comment by Rumbie-Mudzie7** [comment]
Please refer to this link to improve your readme
https://github.com/Rumbie-Mudzie7/project-mint.com

**Comment by Hlamulo-Mav** [comment]
Thank you. We will work on it.
